# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:day/:title.html

# Setup
title:               Badr Interactive Engineering
tagline:             'Berbagi pengalaman untuk menciptakan software yang lebih baik'
description:         'Repository ilmu dan pengalaman tim Engineering Badr Interactive'
url:                 https://badr-interactive.github.io
paginate:            5

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-sitemap, jekyll-paginate]

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false
